### ISSUE TITLE
Preparation for submission: adhere to drupal code guidelines

### ISSUE THREAD

**Issue by mkernel** [palasthotel/grid-drupal#1]
Before we can submit the module to drupal.org we have to ensure that the code guidelines are adhered.

@EdwardBock @benthebear @MarcusAbel @greatestview any volunteers?

**Comment by benthebear** [comment]
@mkernel @EdwardBock Ok … I'll do that.

**Comment by benthebear** [comment]
WTF?!

![bildschirmfoto 2017-09-29 um 13 07 40](https://user-images.githubusercontent.com/49137/31013627-351ac0ea-a517-11e7-83e8-cf3fe38fe945.png)

I must have been really drunk, three an a half year ago … 

@mkernel Is that even relevant by now? Have we already published _anything_ in drupal.org?

**Comment by mkernel** [comment]
Yes it is. No we have not.
