### ISSUE TITLE
Drupal 8 Active Theme

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-drupal#12]
@mkernel 
I tried my very best but could not find a way to get the path to active theme for grid without breaking the grid editor.

This one works in frontend:

```
$theme_path = DRUPAL_ROOT.'/'.\Drupal::theme()->getActiveTheme()->getName();
$templates[] = $theme_path.'/grid';
```

But it seems to destroy the grid editor. Could you please have a look at https://github.com/palasthotel/grid-drupal/blob/8.x-1.x-dev/grid.module#L115-L121 ?

**Comment by mkernel** [comment]
We found a solution together, right? right?
