### ISSUE TITLE
Grid dependencies (to modules: image and file)

### ISSUE THREAD

**Issue by SaschaHagemann** [palasthotel/grid-drupal#15]
Dear @EdwardBock + @mkernel 

When using a D7-minimal-installation I discovered one (or two) more dependencies when installing grid:
- contrib module `image`
- contrib module `file` (for the file field type)

With these 2 modules missing the grid-config-page `/admin/config/grid/settings` throws an error `Fatal error: Call to undefined function image_styles()`.

**Comment by SaschaHagemann** [comment]
Another (kind of) dependency: 

Grid only looks good with the Drupal-Admin-Theme `seven` (https://www.drupal.org/project/seven), not so good with `bartik`, `garland` etc. - So at least we should recommend to set `seven` as the admin theme via `/admin/appearance`-> `Administration theme` in your Drupal.

**Comment by EdwardBock** [comment]
Was never an issue again
