### ISSUE TITLE
D8: html box is not editable when enabling JS aggregation

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid-drupal#18]
When enabling JS aggregation on D8, all html boxes on all grid pages are no longer editable:

(copy & paste was not formatted properly)

![bildschirmfoto 2017-11-21 um 13 44 11](https://user-images.githubusercontent.com/2060276/33073137-2a0af920-cec2-11e7-899f-7326dd177cc6.png)

**Comment by EdwardBock** [comment]
Fixed by accident with new update
