### ISSUE TITLE
Submit to drupal.org

### ISSUE THREAD

**Issue by mkernel** [palasthotel/grid-drupal#2]
@benthebear @MarcusAbel @SaschaHagemann @EdwardBock any volunteers?

**Comment by benthebear** [comment]
@mkernel @EdwardBock @SaschaHagemann @MarcusAbel Ok. I'll do that. We'll start with a smaller Module, right? 
Did we already decide which one?

**Comment by mkernel** [comment]
@benthebear We could start by building westie up to "override term pages" or sth. like that. However from reading the documentation on drupal.org we should ensure that the development steps of westie are visible within the repo history - which is a challenge i think.

**Comment by benthebear** [comment]
Ah. Yeah, right. Why should that be a challange? Let's fork Westi into a Repo "Overrider" and rename all Files and Functions. The complete History should be within the fork, shouldn't it?

**Comment by mkernel** [comment]
I read somewhere that the sandbox project should contain a noteworthy versioning history so the reviewer can see there actually happened development. I'm not sure if westie can provide that - is the most current version in its own repo with a "noteworthy" history?

**Comment by mkernel** [comment]
Ah! Found it:

> Get your project into a state you feel is release-ready. Ideally, you would commit the project early and have a track record of several weeks/months of commits so that application reviewers can get an idea of your development and maintenance style.

Source: https://drupal.org/node/1011698

**Comment by EdwardBock** [comment]
@kahta would you take a look at where and how we can submit grid to drupal.org?

**Comment by EdwardBock** [comment]
@kahta do you have any news on this?
