### ISSUE TITLE
Drupal 8: Frontend Editing when Node has Grid

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid-drupal#24]
On our BUR project with D8 we have this issue:
- We enabled Grid support for a specific node type (page).
- We created a Grid for that node (page).
- If we want to edit that node/page (**not** the Grid itself), Drupal shows the frontend theme with inline editing instead of the default backend theme (Seven).

**Comment by EdwardBock** [comment]
I see the problem. But I don't see how you can relate from the problem to the grid module.

Anyway. Something for @mkernel

**Comment by mkernel** [comment]
@greatestview i don't think that that has something to do with grid. Technically there is a way to switch routes (read: URLs) between the admin and the frontend theme. However... grid only switches its own routes into the admin theme. 

So there must be something else going on.
