### ISSUE TITLE
Drupal 8: Default content view is full node, even when teaser is the only option

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid-drupal#25]
On our BUR project with D8 we have this issue:
- We have a Grid.
- In */admin/config/grid/settings* the only checked box in *Supported Displays for nodes within grid* is *Teaser* (»Anrisstext«).
- We place a Content Box inside that Grid, e. g. an article.
- We click Preview or Node View: Instead of a teaser, the box displays the full node view.
- Workaround: We open the grid box and click save without changing anything. We click Preview or Node View: The box is correctly displayed as a teaser.

**Comment by mkernel** [comment]
@greatestview we just fixed that bug - see 1359fc45744e26bf37c107a13d5543bfbe67c802
