### ISSUE TITLE
Performance Aggregation break HTML Box

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-drupal#31]
@mkernel @arnalyse 

We have the problem that the performance -> JS and CSS aggregation activation breaks the html box in the grid editor. Could one of you help me fix that?

**Comment by mkernel** [comment]
@EdwardBock on which drupal major version does this problem occur? 7 or 8?

**Comment by EdwardBock** [comment]
It's Drupal 8 . You can check the DC-D8 project.

**Comment by EdwardBock** [comment]
This seems to be fixed by accident with the new grid release.
